name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Update version
        run: |
          cat > update-version.js << 'EOF'
          const fs = require('fs');
          const { execSync } = require('child_process');
          
          try {
            // Get latest tag
            const tag = execSync('git describe --tags --abbrev=0').toString().trim() || 'v0.0.0';
            console.log('Latest tag:', tag);
            
            // Read HTML file
            const filePath = 'index.html';
            let html = fs.readFileSync(filePath, 'utf8');
            
            // Update version badge
            const newBadge = `<div class="version-badge"><a href="https://github.com/lxmfy/lxmfy/releases/tag/${tag}">${tag}</a></div>`;
            html = html.replace(/<div class="version-badge">.*?<\/div>/s, newBadge);
            
            // Write back to file
            fs.writeFileSync(filePath, html);
            console.log('Version updated successfully');
          } catch (error) {
            console.error('Error:', error);
            process.exit(1);
          }
          EOF
          node update-version.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 